---
roles: []
collections:
  - name: community.crypto
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: google.cloud
    source: https://galaxy.ansible.com
