---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.0
    hooks:
      - id: prettier
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        exclude: ^node_modules/
      - id: check-ast
        exclude: ^node_modules/
      - id: check-builtin-literals
        exclude: (^node_modules/|^roles/misc/freeipa)
      - id: check-case-conflict
        exclude: ^node_modules/
      - id: check-docstring-first
        exclude: ^node_modules/
      - id: check-json
        exclude: ^node_modules/
      - id: check-merge-conflict
        exclude: ^node_modules/
      - id: check-symlinks
        exclude: ^node_modules/
      - id: check-vcs-permalinks
        exclude: ^node_modules/
      - id: check-xml
        exclude: ^node_modules/
      - id: check-yaml
        exclude: ^node_modules/
      - id: debug-statements
        exclude: ^node_modules/
      - id: detect-private-key
        exclude: ^node_modules/
      - id: end-of-file-fixer
        exclude: ^node_modules/
      - id: mixed-line-ending
        exclude: ^node_modules/
      - id: requirements-txt-fixer
        exclude: ^node_modules/
      - id: sort-simple-yaml
        exclude: ^node_modules/
      - id: trailing-whitespace
        exclude: ^node_modules/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^roles/misc/freeipa
  #  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #    rev: v1.0.3
  #    hooks:
  #      - id: python-bandit-vulnerability-check
  #        args: [-l, --recursive, -x, tests]
  #        files: .py$
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.7
    hooks:
      - id: ansible-lint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.25.0
    hooks:
      - id: yamllint
#  - repo: https://github.com/markdownlint/markdownlint
#    rev: v0.11.0
#    hooks:
#      - id: markdownlint
