---
stages:
  - update
  - lint
  - test

variables:
  ANSIBLE_CONFIG: ${CI_PROJECT_DIR}/ansible.cfg

include:
  - local: .gitlab/ci/lint/ansible-lint.gitlab-ci.yml
  - local: .gitlab/ci/lint/eslint.gitlab-ci.yml
  - local: .gitlab/ci/lint/python/flake8.gitlab-ci.yml
  - local: .gitlab/ci/lint/hadolint.gitlab-ci.yml
  - local: .gitlab/ci/lint/prettier.gitlab-ci.yml
  - local: .gitlab/ci/lint/shellcheck.gitlab-ci.yml
  - local: .gitlab/ci/lint/yamllint.gitlab-ci.yml
  - local: .gitlab/ci/test/ansible/playbook.gitlab-ci.yml
  - local: .gitlab/ci/test/ansible/playbook.macos.gitlab-ci.yml
  - local: .gitlab/ci/test/ansible/playbook.windows.gitlab-ci.yml
  - local: .gitlab/ci/update/project.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
