---
version: "3"

output: prefixed

env:
  GALAXY_NAMESPACE: professormanhattan
  REPOSITORY_SUBTYPE: playbook
  REPOSITORY_TYPE: ansible

includes:
  common: ./.common/taskfiles-playbook/Taskfile-common.yml
  ansible: ./.common/taskfiles-playbook/Taskfile-ansible.yml
  fix: ./.common/taskfiles-playbook/Taskfile-fix.yml
  lint: ./.common/taskfiles-playbook/Taskfile-lint.yml
  software: ./.common/taskfiles-playbook/Taskfile-{{OS}}.yml
