---
version: '3'

output: interleaved

env:
  GALAXY_NAMESPACE: installdoctor
  REPOSITORY_SUBTYPE: playbook
  REPOSITORY_TYPE: ansible

includes:
  ansible: ./taskfiles/ansible/Taskfile.yml
  ansible:ansibler: ./taskfiles/ansible/Taskfile-ansibler.yml
  ansible:test: ./taskfiles/ansible/Taskfile-test.yml
  common: ./taskfiles/common/Taskfile.yml
  common:update: ./taskfiles/common/Taskfile-update.yml
  fix: ./taskfiles/Taskfile-fix.yml
  git: ./taskfiles/Taskfile-git.yml
  image: ./taskfiles/Taskfile-image.yml
  install: ./taskfiles/Taskfile-install.yml
  lint: ./taskfiles/Taskfile-lint.yml
  security: ./taskfiles/Taskfile-security.yml
  vscode: ./taskfiles/Taskfile-vscode.yml

tasks:
  start:
    desc: Set up the project and refresh it with the latest changes
    summary: |
      # Set up the project

      This task will scaffold the project with the latest upstream changes
      and ensure your development environment has all the dependencies installed.

      **Example usage:**
      `task start`
    cmds:
      - task: common:update
