version: '3'

env:
  GALAXY_NAMESPACE:
    sh: yq e '.galaxy_info.namespace' meta/main.yml
  GALAXY_ROLE_NAME:
    sh: yq e '.galaxy_info.role_name' meta/main.yml
  REPOSITORY_SUBTYPE:
    sh: if [ -d environments ]; then echo playbook; else echo role; fi
  REPOSITORY_TYPE: ansible

includes:
  system: ./.common/taskfiles/Taskfile-{{OS}}.yml
  common: ./.common/taskfiles/Taskfile-common.yml
  docs: ./.common/taskfiles/Taskfile-ansible.yml
  type: ./.common/taskfiles/Taskfile-{{.REPOSITORY_TYPE}}.yml

tasks:
  

  lint:

    deps: [lint-ansible, lint-dockerfiles, lint-python, lint-yaml]
