---
version: '3'

output: prefixed

env:
  GALAXY_NAMESPACE: installdoctor
  REPOSITORY_SUBTYPE: playbook
  REPOSITORY_TYPE: ansible

includes:
  ansible: ./.common/taskfiles-playbook/Taskfile-ansible.yml
  common: ./.common/taskfiles-playbook/Taskfile-common.yml
  fix: ./.common/taskfiles-playbook/Taskfile-fix.yml
  image: ./.common/taskfiles-playbook/Taskfile-image.yml
  lint: ./.common/taskfiles-playbook/Taskfile-lint.yml
  npm: ./.common/taskfiles-playbook/Taskfile-npm.yml
  python: ./.common/taskfiles-playbook/Taskfile-python.yml
  security: ./.common/taskfiles-playbook/Taskfile-security.yml
  software: ./.common/taskfiles-playbook/Taskfile-{{OS}}.yml
  test: ./.common/taskfiles-playbook/Taskfile-test.yml
  vscode: ./.common/taskfiles-playbook/Taskfile-vscode.yml
