---
version: '3'

env:
  REPOSITORY_NAME:
    sh: jq -r '.name' package.json | sed 's/.*\///'
  REPOSITORY_NAMESPACE:
    sh: jq -r '.name' package.json | sed 's/@//' | sed 's/\/.*//'
  REPOSITORY_SUBTYPE: role
  REPOSITORY_TYPE: ansible

includes:
  system: ./.common/taskfiles-role/Taskfile-{{OS}}.yml
  common: ./.common/taskfiles-role/Taskfile-common.yml
  fix: ./.common/taskfiles-role/Taskfile-fix.yml
  lint: ./.common/taskfiles-role/Taskfile-lint.yml
  ansible: ./.common/taskfiles-role/Taskfile-ansible.yml
