---
version: '3'

output: prefixed

env:
  GALAXY_NAMESPACE: installdoctor
  REPOSITORY_SUBTYPE: playbook
  REPOSITORY_TYPE: ansible

includes:
  ansible: ./.common/taskfiles-playbook/Taskfile-ansible.yml
  common: ./.common/taskfiles-playbook/Taskfile-common.yml
  fix: ./.common/taskfiles-playbook/Taskfile-fix.yml
  git: ./.common/taskfiles-playbook/Taskfile-git.yml
  image: ./.common/taskfiles-playbook/Taskfile-image.yml
  lint: ./.common/taskfiles-playbook/Taskfile-lint.yml
  npm: ./.common/taskfiles-playbook/Taskfile-npm.yml
  python: ./.common/taskfiles-playbook/Taskfile-python.yml
  security: ./.common/taskfiles-playbook/Taskfile-security.yml
  software: ./.common/taskfiles-playbook/Taskfile-{{OS}}.yml
  test: ./.common/taskfiles-playbook/Taskfile-test.yml
  vscode: ./.common/taskfiles-playbook/Taskfile-vscode.yml

tasks:
  start:
    desc: Set up the project and refresh it with the latest changes
    summary: |
      # Set up the project

      This task will scaffold the project with the latest upstream changes
      and ensure your development environment has all the dependencies installed.

      **Example usage:**
      `task start`
    cmds:
      - task: :common:update
