[tool.poetry]
name = "{{repository.prefix.github}}{{slug}}"
version = "{{version}}"
description = "{{description}}"
authors = ["{{author.name}} <{{author.email}}>"]
license = "{{license}}"
readme = "README.md"
homepage = "{{link.home}}"
documentation = "{{docs.link}}"
keywords = [{{{poetryKeywords}}}]
include = ["CHANGELOG.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.9"
ansible = "^4.8.0"
docker = "^5.0.3"
python-vagrant = "^0.5.15"
pywinrm = ">=0.3.0"

[tool.poetry.dev-dependencies]
ansible-lint = "<5.0.0"
ansibler = "^0.1.14"
black = "^21.10b0"
blocklint = "^0.2.3"
flake8 = "^4.0.1"
mod-ansible-autodoc = "^0.5.7"
molecule-docker = "^1.1.0"
molecule-vagrant = "^0.6.3"
pre-commit-hooks = "^4.0.1"
proselint = "^0.12.0"
yamllint = "^1.26.3"

[tool.poetry.urls]
"Bug Tracker" = "{{repository.gitlab}}{{repository.location.issues.gitlab}}"
"GitHub" = "{{repository.github}}"
"GitLab" = "{{repository.gitlab}}"
"Open Collective" = "{{profile_link.opencollective}}/{{profile.opencollective}}"
"Patreon" = "{{profile_link.patreon}}/{{profile.patreon}}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
