---
version: '3'

vars:
  TEMPLATE_FILE:
    sh: if [ ! -z "{{.CLI_ARGS}}" ]; then echo "{{.CLI_ARGS}}"; else echo "default.packer.json"; fi
  VARIABLES_PATH: .variables.json

tasks:
  build:
    deps:
      - :install:software:kvm
      - :install:software:parallels
      - :install:software:virtualbox
      - :install:software:vmware
    log:
      error: Encountered error while running `packer build`
      start: Running `packer build` for all supported platforms that are installed
      success: Successfully built the Packer images
    cmds:
      - |
        if type qemu-system-x86_64 &> /dev/null; then
          .config/log info 'QEMU is available'
          echo 'KVM' > "$TMP"
        fi
        if [ '{{OS}}' == 'darwin' ] && mdfind -name 'Parallels Desktop.app' &> /dev/null; then
          .config/log info 'Parallels is installed'
          echo 'Parallels' > "$TMP"
        fi
        if type vboxmanage &> /dev/null; then
          .config/log info 'VirtualBox is installed'
          echo 'VirtualBox' > "$TMP"
        fi
        if [ '{{OS}}' == 'linux' ] && type vmware &> /dev/null; then
          .config/log info 'VMWare Workstation is installed'
          echo 'VMWare Workstation' > "$TMP"
        fi
        if [ '{{OS}}' == 'darwin' ] && type vmrun &> /dev/null; then
          .config/log info 'VMWare Fusion is installed'
          echo 'VMWare Fusion' > "$TMP"
        fi

  latestos:
    deps:
      - :install:python:requirements
      - :install:software:jq
    vars:
      TAG:
        sh: jq -r '.variables.latestos_tag' {{.TEMPLATE_FILE}}
    log:
      error: Error running `{{.PYTHON_HANDLE}}latestos {{.TAG}}`
      start: Running `{{.PYTHON_HANDLE}}latestos {{.TAG}}`
      success: Successfully ran `{{.PYTHON_HANDLE}}latestos {{.TAG}}`
    cmds:
      - '{{.PYTHON_HANDLE}}latestos {{.TAG}}'
    status:
      - '[[ "{{.TAG}}}" == "macos" ]] || [ "${container:=}" == "docker" ]'
    preconditions:
      - sh: test -f {{.TEMPLATE_FILE}}
        msg: The `{{.TEMPLATE_FILE}}` file is missing from the root of this project.
