---
version: '3'

tasks:
  docker:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type docker &> /dev/null

  git:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type git &> /dev/null

  jq:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type jq &> /dev/null

  node:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type node &> /dev/null
      - type npm &> /dev/null
      - type npx &> /dev/null

  python:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type python &> /dev/null

  rsync:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type rsync &> /dev/null

  vagrant:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type vagrant &> /dev/null

  virtualbox:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type virtualbox &> /dev/null

  yq:
    cmds:
      - echo "TODO: https://install.doctor script"
    status:
      - type yq &> /dev/null
