---
description: Run the play on the localhost
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  connection_options:
    ansible_become_pass: ${TEST_PASSWORD:-ansible}
    ansible_user: ${USER:-ansible}
scenario:
  create_sequence:
    - dependency
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - prepare
    - converge
    - check
  converge_sequence:
    - dependency
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
  test_sequence:
    - dependency
    - lint
    - cleanup
    - syntax
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
