---
dist: focal
os: linux
language: python
python:
  - '3.8'
git:
  submodules: false

jobs:
  include:
    - name: Ubuntu 20.04 (ARM64)
      os: linux
      dist: focal
      arch: arm64
      language: python
      python:
        - 3.8
      before_install:
        - python --version
        - pip3 install ansible
      script:
        - ROLE_FOLDER=$(basename "$PWD")
        - sed -i "s/CI_ROLE_NAME/${ROLE_FOLDER}/g" tests/test.yml
        - ansible --version
        - ansible-playbook tests/test.yml -i tests/inventory
    - name: Mac OS X 10.15.7
      os: osx
      osx_image: xcode12.2
      language: shell
      before_install:
        - python --version
        - pip3 install ansible
      script:
        - ROLE_FOLDER=$(basename "$PWD")
        - sed -i ".bak" "s/CI_ROLE_NAME/${ROLE_FOLDER}/g" tests/test.yml
        - ansible --version
        - ansible-playbook tests/test.yml -i tests/inventory
    - name: Windows 10
      os: windows
      language: shell
      before_install:
        - choco install python3
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install ansible
      script:
        - ROLE_FOLDER=$(basename "$PWD")
        - sed -i "s/CI_ROLE_NAME/${ROLE_FOLDER}/g" tests/test.yml
        - ansible --version
        - ansible-playbook tests/test.yml -i tests/inventory
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
