---
version: '3'

env:
  GALAXY_NAME:
    sh: yq e '.galaxy_info.role_name' meta/main.yml
  GALAXY_NAMESPACE:
    sh: yq e '.galaxy_info.namespace' meta/main.yml
  REPOSITORY_SUBTYPE: role
  REPOSITORY_TYPE: ansible

includes:
  system: ./.common/taskfiles-role/Taskfile-{{OS}}.yml
  common: ./.common/taskfiles-role/Taskfile-common.yml
  fix: ./.common/taskfiles-role/Taskfile-fix.yml
  lint: ./.common/taskfiles-role/Taskfile-lint.yml
  ansible: ./.common/taskfiles-role/Taskfile-ansible.yml
